/**
 * QuantumClockAI backend endpoints.
 * Production backend runs on Render.
 * No synthetic telemetry is generated by the frontend.
 */

export const REST_BASE = "https://quantumclockai.onrender.com";
export const WS_URL = "wss://quantumclockai.onrender.com/ws/clock";

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${REST_BASE}${path}`, {
    headers: { "content-type": "application/json" },
    ...init,
  });

  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}`);
  }

  return (await response.json()) as T;
}

export function getHealth() {
  return request<unknown>("/health");
}

export function resetSimulation() {
  return request<unknown>("/reset", { method: "POST" });
}