/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as NoiseRouteImport } from './routes/noise'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as QuantumRouteImport } from './routes/quantum'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StabilityRouteImport } from './routes/stability'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiseRoute = NoiseRouteImport.update({
  id: '/noise',
  path: '/noise',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumRoute = QuantumRouteImport.update({
  id: '/quantum',
  path: '/quantum',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StabilityRoute = StabilityRouteImport.update({
  id: '/stability',
  path: '/stability',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/clock': typeof ClockRoute
  '/contact': typeof ContactRoute
  '/environment': typeof EnvironmentRoute
  '/noise': typeof NoiseRoute
  '/overview': typeof OverviewRoute
  '/quantum': typeof QuantumRoute
  '/research': typeof ResearchRoute
  '/stability': typeof StabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/clock': typeof ClockRoute
  '/contact': typeof ContactRoute
  '/environment': typeof EnvironmentRoute
  '/noise': typeof NoiseRoute
  '/overview': typeof OverviewRoute
  '/quantum': typeof QuantumRoute
  '/research': typeof ResearchRoute
  '/stability': typeof StabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/clock': typeof ClockRoute
  '/contact': typeof ContactRoute
  '/environment': typeof EnvironmentRoute
  '/noise': typeof NoiseRoute
  '/overview': typeof OverviewRoute
  '/quantum': typeof QuantumRoute
  '/research': typeof ResearchRoute
  '/stability': typeof StabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/clock'
    | '/contact'
    | '/environment'
    | '/noise'
    | '/overview'
    | '/quantum'
    | '/research'
    | '/stability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/clock'
    | '/contact'
    | '/environment'
    | '/noise'
    | '/overview'
    | '/quantum'
    | '/research'
    | '/stability'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/clock'
    | '/contact'
    | '/environment'
    | '/noise'
    | '/overview'
    | '/quantum'
    | '/research'
    | '/stability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ClockRoute: typeof ClockRoute
  ContactRoute: typeof ContactRoute
  EnvironmentRoute: typeof EnvironmentRoute
  NoiseRoute: typeof NoiseRoute
  OverviewRoute: typeof OverviewRoute
  QuantumRoute: typeof QuantumRoute
  ResearchRoute: typeof ResearchRoute
  StabilityRoute: typeof StabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noise': {
      id: '/noise'
      path: '/noise'
      fullPath: '/noise'
      preLoaderRoute: typeof NoiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum': {
      id: '/quantum'
      path: '/quantum'
      fullPath: '/quantum'
      preLoaderRoute: typeof QuantumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stability': {
      id: '/stability'
      path: '/stability'
      fullPath: '/stability'
      preLoaderRoute: typeof StabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ClockRoute: ClockRoute,
  ContactRoute: ContactRoute,
  EnvironmentRoute: EnvironmentRoute,
  NoiseRoute: NoiseRoute,
  OverviewRoute: OverviewRoute,
  QuantumRoute: QuantumRoute,
  ResearchRoute: ResearchRoute,
  StabilityRoute: StabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
